version: "3.0"
services:
  db:
    image: docker.io/library/mariadb:latest
    environment: 
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=9x8A7@6b
      - MYSQL_ROOT_PASSWORD=9x8A7@6b
    volumes:
      - wpdb_vol:/var/lib/mysql
    

  wp:
    image: docker.io/library/wordpress:latest
    volumes:
      - wpsite_vol:/var/www
    depends_on: 
      - db
    ports:
      - 8080:80
  
volumes:
  wpsite_vol: {}
  wpdb_vol: {}

